### ISSUE TITLE
The evaluation function is read in an inconsistent way

### ISSUE THREAD

**Issue by Breeze-Zero** [CmrxRecon/CMRxRecon#3]
I notice that h5py reads the dimensions [time,sz,sx,sy], while mat73, sigpy, and matlab read the dimensions [sy,sx,sz,time](in reverse order).If the read function uses h5py, why does the evaluation function use the last two dimensions as time and sz?

**Comment by Breeze-Zero** [comment]
Also, here is my feedback after uploading the results. You can see that the docker code is evaluated using scio.loadmat, while the public GitHub code uses h5py.

STDERR: 2023-06-13T14:23:33.253508784Z 	Traceback (most recent call last):
STDERR: 2023-06-13T14:23:33.253513429Z 	  File "/app/Main_Score.py", line 1041, in <module>
STDERR: 2023-06-13T14:23:33.253518744Z 	['MultiCoil', 'SingleCoil']
STDERR: 2023-06-13T14:23:33.253522667Z 	    main()
STDERR: 2023-06-13T14:23:33.253531669Z 	  File "/app/Main_Score.py", line 317, in main
STDERR: 2023-06-13T14:23:33.253535730Z 	    flag_folder_lax_04_Single, missing_folders_lax_04_Single, submit_folders_lax_04_Single, flag_file_lax_04_Single, different_sizes_lax_04_Single, missing_files_lax_04_Single, openfail_files_lax_04_Single, complete_folders_lax_04_Single, num_file_lax_04_Single = check_mapping_data(
STDERR: 2023-06-13T14:23:33.253540713Z 	  File "/app/Main_Score.py", line 216, in check_mapping_data
STDERR: 2023-06-13T14:23:33.253545633Z 	    flag_file, different_sizes, missing_files, openfail_files, complete_folders, num_file = check_mat_files(gt_dir, target_dir,
STDERR: 2023-06-13T14:23:33.253550506Z 	  File "/app/Main_Score.py", line 195, in check_mat_files
STDERR: 2023-06-13T14:23:33.253555171Z 	    dataset2 = loadmat(mat_file_path2)
STDERR: 2023-06-13T14:23:33.253560262Z 	  File "/app/loadFun.py", line 16, in loadmat
STDERR: 2023-06-13T14:23:33.253564910Z 	    mat_file = scio.loadmat(filename)
STDERR: 2023-06-13T14:23:33.253570258Z 	  File "/usr/local/lib/python3.9/site-packages/scipy/io/matlab/_mio.py", line 226, in loadmat
STDERR: 2023-06-13T14:23:33.253575446Z 	    MR, _ = mat_reader_factory(f, **kwargs)
STDERR: 2023-06-13T14:23:33.253580816Z 	  File "/usr/local/lib/python3.9/site-packages/scipy/io/matlab/_mio.py", line 74, in mat_reader_factory
STDERR: 2023-06-13T14:23:33.253585856Z 	    mjv, mnv = _get_matfile_version(byte_stream)
STDERR: 2023-06-13T14:23:33.253590881Z 	  File "/usr/local/lib/python3.9/site-packages/scipy/io/matlab/_miobase.py", line 251, in _get_matfile_version
STDERR: 2023-06-13T14:23:33.253596779Z 	    raise ValueError('Unknown mat file type, version %s, %s' % ret)
STDERR: 2023-06-13T14:23:33.253602206Z 	ValueError: Unknown mat file type, version 0, 0

**Comment by Breeze-Zero** [comment]
And the evaluation code reads the mat field saying 'img4ranking', but the GitHub example reads only the 'data' field and doesn't specify it. Probably because of the first competition, these small problems delayed us a lot of time.

STDERR: 2023-06-13T15:18:30.968167600Z 	  File "/app/Main_Score.py", line 317, in main
STDERR: 2023-06-13T15:18:30.968169968Z 	    flag_folder_lax_04_Single, missing_folders_lax_04_Single, submit_folders_lax_04_Single, flag_file_lax_04_Single, different_sizes_lax_04_Single, missing_files_lax_04_Single, openfail_files_lax_04_Single, complete_folders_lax_04_Single, num_file_lax_04_Single = check_mapping_data(
STDERR: 2023-06-13T15:18:30.968172487Z 	  File "/app/Main_Score.py", line 216, in check_mapping_data
STDERR: 2023-06-13T15:18:30.968174704Z 	    flag_file, different_sizes, missing_files, openfail_files, complete_folders, num_file = check_mat_files(gt_dir, target_dir,
STDERR: 2023-06-13T15:18:30.968176925Z 	  File "/app/Main_Score.py", line 195, in check_mat_files
STDERR: 2023-06-13T15:18:30.968179067Z 	    dataset2 = loadmat(mat_file_path2)
STDERR: 2023-06-13T15:18:30.968181119Z 	  File "/app/loadFun.py", line 18, in loadmat
STDERR: 2023-06-13T15:18:30.968183216Z 	    dataset = mat_file['img4ranking']
STDERR: 2023-06-13T15:18:30.968185255Z 	KeyError: 'img4ranking'

**Comment by ChengYanHuPI** [comment]
We suggest you to run the demo recon code we provided to better know the requirement.
Besides, we will provide the directory structure and data dimensions of all gold standard data for the validation phase as a reference soon.
<https://github.com/CmrxRecon/CMRxRecon/tree/main/CMRxReconDemo>
[CMRxRecon.png]
CMRxRecon/CMRxReconDemo at main · CmrxRecon/CMRxRecon<https://github.com/CmrxRecon/CMRxRecon/tree/main/CMRxReconDemo>
github.com<https://github.com/CmrxRecon/CMRxRecon/tree/main/CMRxReconDemo>

Best regards,
CMRxRecon Team

2023年6月13日 22:43，Breeze. ***@***.***> 写道：



I notice that h5py reads the dimensions [time,sz,sx,sy], while mat73, sigpy, and matlab read the dimensions [sy,sx,sz,time](in reverse order).If the read function uses h5py, why does the evaluation function use the last two dimensions as time and sz?

**Comment by ChengYanHuPI** [comment]
The issue has been resolved. Please try resubmitting the task.


Best regards,
CMRxRecon Team

2023年6月13日 22:44，Breeze. ***@***.***> 写道：



Also, here is my feedback after uploading the results. You can see that the docker code is evaluated using scio.loadmat, while the public GitHub code uses h5py.

STDERR: 2023-06-13T14:23:33.253508784Z Traceback (most recent call last):
STDERR: 2023-06-13T14:23:33.253513429Z File "/app/Main_Score.py", line 1041, in
STDERR: 2023-06-13T14:23:33.253518744Z ['MultiCoil', 'SingleCoil']
STDERR: 2023-06-13T14:23:33.253522667Z main()
STDERR: 2023-06-13T14:23:33.253531669Z File "/app/Main_Score.py", line 317, in main
STDERR: 2023-06-13T14:23:33.253535730Z flag_folder_lax_04_Single, missing_folders_lax_04_Single, submit_folders_lax_04_Single, flag_file_lax_04_Single, different_sizes_lax_04_Single, missing_files_lax_04_Single, openfail_files_lax_04_Single, complete_folders_lax_04_Single, num_file_lax_04_Single = check_mapping_data(
STDERR: 2023-06-13T14:23:33.253540713Z File "/app/Main_Score.py", line 216, in check_mapping_data
STDERR: 2023-06-13T14:23:33.253545633Z flag_file, different_sizes, missing_files, openfail_files, complete_folders, num_file = check_mat_files(gt_dir, target_dir,
STDERR: 2023-06-13T14:23:33.253550506Z File "/app/Main_Score.py", line 195, in check_mat_files
STDERR: 2023-06-13T14:23:33.253555171Z dataset2 = loadmat(mat_file_path2)
STDERR: 2023-06-13T14:23:33.253560262Z File "/app/loadFun.py", line 16, in loadmat
STDERR: 2023-06-13T14:23:33.253564910Z mat_file = scio.loadmat(filename)
STDERR: 2023-06-13T14:23:33.253570258Z File "/usr/local/lib/python3.9/site-packages/scipy/io/matlab/_mio.py", line 226, in loadmat
STDERR: 2023-06-13T14:23:33.253575446Z MR, _ = mat_reader_factory(f, **kwargs)
STDERR: 2023-06-13T14:23:33.253580816Z File "/usr/local/lib/python3.9/site-packages/scipy/io/matlab/_mio.py", line 74, in mat_reader_factory
STDERR: 2023-06-13T14:23:33.253585856Z mjv, mnv = _get_matfile_version(byte_stream)
STDERR: 2023-06-13T14:23:33.253590881Z File "/usr/local/lib/python3.9/site-packages/scipy/io/matlab/_miobase.py", line 251, in _get_matfile_version
STDERR: 2023-06-13T14:23:33.253596779Z raise ValueError('Unknown mat file type, version %s, %s' % ret)
STDERR: 2023-06-13T14:23:33.253602206Z ValueError: Unknown mat file type, version 0, 0

**Comment by fzimmermann89** [comment]
You mentioned above that you will
"[provide] data dimensions of all gold standard data for the validation phase as a reference soon.

Are the dimensions of the gold standard data used in validation after cropping for each file already listed somewhere?
It would be nice to have access to one of the validation ground truth files to check if we are cropping the data correctly...
